### PR TITLE
Added 24.04 base

### PR DESCRIPTION
**Pull request by beliaev-maksim**

### CODE REVIEW

**Comment by addyess** [comment]
If i'm not correct, please tell me -- but i've heard noble is  not supported with charmcraft 2.x.   I'd love to be suprised

**Comment by addyess** [comment]
/canonical/self-hosted-runners/run-workflows 1fa151e880a19d6f9b1a66b0f5cbf3b022f38c52

**Review by addyess — APPROVED** [review]
I looked at the manifests created and they look sane. I have no idea if this works on juju yet.

**Comment by beliaev-maksim** [comment]
@addyess we are not building on noble but need to execute on noble
Should be irrelevant of charmcraft

**Comment by addyess** [comment]
> @addyess we are not building on noble but need to execute on noble
> Should be irrelevant of charmcraft

Perfect.  Let's go

**Pull request merged**
